export const EventTypes = {
  VALUE_CHANGED: 'VALUE_CHANGED',
  ACTION_TRIGGERED: 'ACTION_TRIGGERED',
  CHILD_ADDED: 'CHILD_ADDED',
  CHILD_REMOVED: 'CHILD_REMOVED',
  STATE_CHANGED: 'STATE_CHANGED'
};